packages:
- '.'

- location:
    git: https://github.com/reflex-frp/reflex.git # reflex-0.5
    commit: a1092192c61f3dec924a8e2686dfe3440681bab3
  extra-dep: true

- location:
    git: https://github.com/EugeneN/haskell-virtualdom.git
    commit: 8e4aaf2b28fb420e6be6b40a4a4a856d612a7a62
  extra-dep: true
# - location: '../../haskell-virtualdom'

- location:
    git: https://github.com/bennofs/reflex-host.git
    commit: 219c162bec3c996ec59acde2fba92a666ccf0c4f
  extra-dep: true


# resolver: lts-6.13
# compiler: ghcjs-0.2.0.9006013_ghc-7.10.3
# compiler-check: match-exact
# setup-info:
#   ghcjs:
#     source:
#       ghcjs-0.2.0.9006013_ghc-7.10.3:
#          url: "http://tolysz.org/ghcjs/lts-6.13-9006013.tar.gz"
#          sha1: "7ae7c6571e0fc7642701af3d8a63739369e0f6e8"

resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
           url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
           sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9

extra-deps:
- reflex-0.5.0
- ref-tf-0.4.0.1
- mime-0.4.0.2
- prim-uniq-0.1.0.1
- zenc-0.1.1
- ghcjs-dom-0.9.1.1
- jsaddle-0.9.3.0
- constraints-0.9.1
- ghcjs-dom-jsffi-0.9.1.1
- dependent-map-0.2.4.0
- lens-4.15.3
- th-abstraction-0.2.3.0
- kan-extensions-5.0.2
# - virtualdom-0.1.0.0

ghc-options:
    "*": -DGHCJS_BROWSER
